name: hidable
description: Widget, that can make any static located widget hidable (scroll to hide).
version: 1.0.3
homepage: https://github.com/anonistas/hidable
issue_tracker: https://github.com/anonistas/hidable/issues
documentation: https://github.com/anonistas/hidable#readme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
